services:
  backend-dev-light:
    profiles: [ "dev-light" ]
    ports:
      - "3000:3000"
    networks:
      dev-network:
        ipv4_address: 172.16.100.200
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile.dev-light
    volumes:
      - ./backend/.secrets:/app/.secrets
    depends_on:
      - postgres-dev
    develop:
      watch:
        - action: rebuild
          path: ./backend/build

  backend-dev:
    profiles: [ "dev" ]
    ports:
      - "3000:3000"
    networks:
      dev-network:
        ipv4_address: 172.16.100.200
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/.secrets:/app/.secrets
    depends_on:
      - postgres-dev
    develop:
      watch:
        - action: rebuild
          path: ./backend

  postgres-dev:
    profiles: [ "dev", "dev-light" ]
    ports:
      - "5433:5432"
    image: postgres:17-alpine
    networks:
      dev-network:
        ipv4_address: 172.16.100.201
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backend/src/main/resources/postgres/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}

  pgadmin:
    profiles: [ "dev", "dev-light" ]
    image: dpage/pgadmin4:9.4
    networks:
      dev-network:
        ipv4_address: 172.16.100.202
    ports:
      - "15432:80"
    volumes:
      - ./pgadmin/servers_dev.json:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-dev@mail.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-development}
    depends_on:
      - postgres-dev

volumes:
  postgres_data:

networks:
  dev-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.100.0/24
    internal: true
    # driver_opts:
    #   com.docker.network.bridge.gateway_mode_ipv4: isolated
