FROM eclipse-temurin:21-jdk-alpine AS builder

WORKDIR /app

COPY gradlew .
COPY gradle ./gradle
COPY build.gradle .
COPY settings.gradle .

COPY src ./src

RUN chmod +x gradlew

RUN ./gradlew bootJar --no-daemon

FROM eclipse-temurin:21-jre-alpine
LABEL authors="haziqam"

WORKDIR /app

COPY --from=builder /app/build/libs/app-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 3000

CMD ["java", "-jar", "app.jar", "--spring.profiles.active=dev"]