FROM eclipse-temurin:21-jre-alpine

LABEL authors="haziqam"

WORKDIR /app

COPY build/libs/app-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 3000

CMD ["java", "-jar", "app.jar", "--spring.profiles.active=dev"]
